const express = require("express")
const cors = require("cors")
const connectDb = require("./Connection")
const categoryRouter = require("./Category/CategoryRouter")
const GalleryRouter = require("./Gallery/GalleryRouter")
const galleryController = require("./Gallery/GalleryController")
const productRouter = require("./Product/ProductRouter")
const productController = require("./Product/ProductController")
const userRouter = require("./User/UserRouter")
const cartRouter = require("./Cart/CartRouter")
const addressRouter = require("./Address/AddressRouter")
const orderRouter = require("./Order/OrederRouter")
require("dotenv").config();

const app = express()
connectDb()
app.use(cors())
app.use(express.json())
// galleryController.modifiProduct()
app.use("/public", express.static("./public"))
app.use("/category", categoryRouter)
app.use("/gallery", GalleryRouter)
app.use("/product", productRouter)
app.use("/user", userRouter)
app.use("/cart", cartRouter)
app.use("/address", addressRouter)
app.use("/order", orderRouter)


app.listen(process.env.PORT || 5000, () => {
    console.log("Server Started")
})